project:
  name: EFI_v4

configurations:
  - name: SimTests
    target: ARsim
    simulation: false
    arSimHost: localhost
    arSimPort: 82
    arSimOpcUaPort: 4840
    pviPort: 11169
    arSimTimeZoom: "+2"
    arSimStartupDelaySeconds: 6
    variants:
      - name: MachineModel
        restartSimAfterWrite: true
        sweep:
          variable: "ns=6;s=::AsGlobalPV:gSimMachine.Parameters.MachineType"
          type: int
          values:
            # - { name: SIM_MACHINE_REAL,                value: 0  }
            - { name: SIM_MACHINE_2B12BAR,             value: 1  }
            # - { name: SIM_MACHINE_1B6BAR,              value: 2  }
            - { name: SIM_MACHINE_1B2BAR,              value: 3  }
            # - { name: SIM_MACHINE_P5_WAT,              value: 4  }
            # - { name: SIM_MACHINE_P4_CBK,              value: 5  }
            # - { name: SIM_MACHINE_S1400_VAC_PWRLNK,    value: 6  }
            # - { name: SIM_MACHINE_S1400_VAC_CAN,       value: 7  }
            # - { name: SIM_MACHINE_NZ2,                 value: 8  }
            # - { name: SIM_MACHINE_NZ2_UV,              value: 9  }
            # - { name: SIM_MACHINE_NZ2_UV_WHITE,        value: 10 }
            # - { name: SIM_MACHINE_CUBE,                value: 11 }
            # - { name: SIM_MACHINE_CUBE_GULLIVER,       value: 12 }
            # - { name: SIM_MACHINE_MECANO_UV_WHITE,     value: 13 }
            # - { name: SIM_MACHINE_MECANO_UV_OPV,       value: 14 }
            # - { name: SIM_MACHINE_MECANO_UV_WHITE_OPV, value: 15 }
  # - name: SimDryer
    # target: ARsim
    # simulation: false
    # arSimHost: localhost
    # arSimPort: 83
    # pviPort: 11170
    # arSimTimeZoom: "+2"
    # arSimStartupDelaySeconds: 6

tests:
  perConfiguration:
    SimTests:
      - FunctionsTests
      - PrepareMachine
      # - BeltTests
      - ConsentTests
      # - CleaningTests
      # - LineTests
      # - TrVacuumTests
      # - BlockTests
      # - Cube
    SimDryer:
      - FunctionsTests
      - PrepareDryer
      - BeltTests

pipeline:
  steps: [ build, package, deploy, test, report ]
