
(* TODO: Add your comment here *)
FUNCTION DintTransfer
	
// Out1	
	LSint.0:=In.0;
	LSint.1:=In.1;
	LSint.2:=In.2;
	LSint.3:=In.3;
	LSint.4:=In.4;
	LSint.5:=In.5;
	LSint.6:=In.6;
	LSint.7:=In.7;
	LSint.8:=In.8;
	LSint.9:=In.9;
	LSint.10:=In.10;
	LSint.11:=In.11;
	LSint.12:=In.12;
	LSint.13:=In.13;
	LSint.14:=In.14;
	LSint.15:=In.15;
	
	
// Out2	
	MSint.0:=In.16;
	MSint.1:=In.17;
	MSint.2:=In.18;
	MSint.3:=In.19;
	MSint.4:=In.20;
	MSint.5:=In.21;
	MSint.6:=In.22;
	MSint.7:=In.23;
	MSint.8:=In.24;
	MSint.9:=In.25;
	MSint.10:=In.26;
	MSint.11:=In.27;
	MSint.12:=In.28;
	MSint.13:=In.29;
	MSint.14:=In.30;
	MSint.15:=In.31;	
	
	DintTransfer := TRUE;
	
END_FUNCTION
