
TYPE
	SimRegisterState : 
		(
		SIMR_IDLE,
		SIMR_CREATE_MAIN,
		SIMR_CREATING_MAIN,
		SIMR_CREATE_YEAR,
		SIMR_CREATING_YEAR,
		SIMR_CREATE_FILEREG,
		SIMR_CREATING_FILEREG,
		SIMR_IDLE_MAIN,
		SIMR_STOPPED
		);
END_TYPE
