<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.5.4.123 SP?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Groups test cases for addition">CleaningTests.c</File>
    <File Description="PVs for the program and test suite" Private="true">CleaningTests.var</File>
    <File Description="Handling of program and test suite">testSuite.c</File>
    <File Description="Auto generated code">autoGeneratedFile.c</File>
    <File Description="Updates test programs within the current package">Update_TestPrograms_in_current_location.bat</File>
  </Files>
</Program>