
# To install it type in command line: pip install openpyxl
from openpyxl import load_workbook
import math

import os, shutil


def copytree(src, dst, symlinks=False, ignore=None):
    for item in os.listdir(src):
        s = os.path.join(src, item)
        d = os.path.join(dst, item)
        if os.path.isdir(s):
            shutil.copytree(s, d, symlinks, ignore)
        else:
            shutil.copy2(s, d)


def replace_text_in_file(filename, oldstr, newstr):
    global f, newText
    with open(filename) as f:
        newText = f.read().replace(oldstr, newstr)
    with open(filename, "w") as f:
        f.write(newText)


print("\n\nProgram to create new test. By Jorge Murria. Version 0.1")
print("Press enter to cancel\n")
newName = input("Enter the name of the new test: ")
shutil.copytree('TemplateTests', newName)

FileName = '.\\' + newName + '\TemplateTests.c'
replace_text_in_file(FileName, 'TemplateTests', newName)

FileName = '.\\' + newName + '\ANSIC.prg'
replace_text_in_file(FileName, 'TemplateTests', newName)

FileName = '.\\' + newName + '\\' + 'autoGeneratedFile.c'
replace_text_in_file(FileName, 'TemplateTests', newName)

FileName = '.\\' + newName + '\TemplateTests.var'
replace_text_in_file(FileName, 'TemplateTests', newName)


os.rename('.\\' + newName + '\TemplateTests.c', '.\\' + newName + '\\' + newName + '.c')
os.rename('.\\' + newName + '\TemplateTests.var', '.\\' + newName + '\\' + newName + '.var')

print("\nThe TemplateTest has been properly replicated as " + newName)
newName = input("Press enter to finish")

